name: Marul_Tarlasi
description: Marul Tarlası Mobil Uygulama.

publish_to: "none"

version: 0.1.0

environment:
    sdk: ">=2.17.5 <3.0.0"

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^1.0.2
    font_awesome_flutter: ^10.1.0
    animations: ^2.0.3
    http: ^1.2.2
    package_info_plus: ^8.0.2
    share_plus: ^10.0.2
    easy_url_launcher: ^0.0.7
    community_material_icon: ^5.9.55
    firebase_auth: ^5.4.0
    firebase_core: ^3.10.0
    firebase_analytics: ^11.4.0
    google_sign_in: ^6.2.2
    flutter_svg: ^2.0.17
    path_provider: ^2.0.8
    firebase_messaging: ^15.2.0
    permission_handler: ^11.3.1

dev_dependencies:
    flutter_launcher_icons: ^0.13.1
    flutter_lints: ^5.0.0
    flutter_test:
        sdk: flutter

flutter_icons:
    android: {
        "generate": true
    }
    web: {
        "generate": true
    }
    windows: {
        "generate": true
    }
    image_path: "assets/logo.jpg"

flutter:
    uses-material-design: true

    assets:
        - assets/images/
        - assets/fitness_app/
        - assets/hasta/
        - assets/introduction_animation/
        - assets/fonts/
        - assets/

    fonts:
        - family: WorkSans
          fonts:
              - asset: assets/fonts/WorkSans-Regular.ttf
              - asset: assets/fonts/WorkSans-Medium.ttf
                weight: 500
              - asset: assets/fonts/WorkSans-SemiBold.ttf
                weight: 600
              - asset: assets/fonts/WorkSans-Bold.ttf
                weight: 700
        - family: Roboto
          fonts:
              - asset: assets/fonts/Roboto-Bold.ttf
              - asset: assets/fonts/Roboto-Regular.ttf
              - asset: assets/fonts/Roboto-Medium.ttf
                weight: 400
