name: Marul_Tarlasi
description: A new Flutter project.

publish_to: "none"

version: 0.1.0

environment:
    sdk: ">=2.17.5 <3.0.0"

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^1.0.2
    font_awesome_flutter: ^10.1.0
    flutter_rating_bar: ^4.0.1
    intl: ^0.19.0
    animations: ^2.0.3
    http: ^1.2.2
    package_info_plus: ^8.0.2
    share_plus: ^10.0.2
    easy_url_launcher: ^0.0.7
    community_material_icon: ^5.9.55
    firebase_auth: ^5.4.0
    cloud_firestore: ^5.6.1
    firebase_data_connect: ^0.1.2+6
    firebase_core: ^3.10.0
    firebase_analytics: ^11.4.0
    google_sign_in: ^6.2.2
    flutter_svg: ^2.0.17
    flutter_otp_text_field: ^1.1.1
    path_provider: ^2.0.8

dev_dependencies:
    flutter_launcher_icons: ^0.13.1
    flutter_test:
        sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter_icons:
    android: {
        "generate": true
    }
    web: {
        "generate": true
    }
    windows: {
        "generate": true
    }
    image_path: "assets/logo.jpg"
# The following section is specific to Flutter.
flutter:
    # The following line ensures that the Material Icons font is
    # included with your application, so that you can use the icons in
    # the material Icons class.
    uses-material-design: true

    # To add assets to your application, add an assets section, like this:
    assets:
        - assets/images/
        - assets/fitness_app/
        - assets/hotel/
        - assets/introduction_animation/
        - assets/fonts/
        - assets/
        - assets/icons/

    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware.

    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages

    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
    fonts:
        - family: WorkSans
          fonts:
              - asset: assets/fonts/WorkSans-Regular.ttf
              - asset: assets/fonts/WorkSans-Medium.ttf
                weight: 500
              - asset: assets/fonts/WorkSans-SemiBold.ttf
                weight: 600
              - asset: assets/fonts/WorkSans-Bold.ttf
                weight: 700
        - family: Roboto
          fonts:
              - asset: assets/fonts/Roboto-Bold.ttf
              - asset: assets/fonts/Roboto-Regular.ttf
              - asset: assets/fonts/Roboto-Medium.ttf
                weight: 400
    #
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages
